In [1]:
# Imports
import geopandas as gpd
import pandas as pd

In [2]:
counties = gpd.read_file(
    "/data/raw/tl_2024_us_county.zip"
)

counties.head()

,STATEFP,COUNTYFP,COUNTYNS,GEOID,GEOIDFQ,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,31,039,00835841,31039,0500000US31039,Cuming,Cuming County,06,H1,G4020,NaN,NaN,NaN,A,1477563042,10772508,+41.9158651,-096.7885168,"POLYGON ((-96.55525 41.82892, -96.55524 41.827..."
1,53,069,01513275,53069,0500000US53069,Wahkiakum,Wahkiakum County,06,H1,G4020,NaN,NaN,NaN,A,680980773,61564428,+46.2946377,-123.4244583,"POLYGON ((-123.72755 46.2645, -123.72756 46.26..."
2,35,011,00933054,35011,0500000US35011,De Baca,De Baca County,06,H1,G4020,NaN,NaN,NaN,A,6016818941,29090018,+34.3592729,-104.3686961,"POLYGON ((-104.89337 34.08894, -104.89337 34.0..."
3,31,109,00835876,31109,0500000US31109,Lancaster,Lancaster County,06,H1,G4020,339,30700,NaN,A,2169269508,22850511,+40.7835474,-096.6886584,"POLYGON ((-96.68493 40.5233, -96.69219 40.5231..."
4,31,129,00835886,31129,0500000US31129,Nuckolls,Nuckolls County,06,H1,G4020,NaN,NaN,NaN,A,1489645201,1718484,+40.1764918,-098.0468422,"POLYGON ((-98.2737 40.1184, -98.27374 40.1224,..."

In [3]:
# Filter to texas
counties = counties[
    counties['STATEFP'] == "48"
]

counties.head()

,STATEFP,COUNTYFP,COUNTYNS,GEOID,GEOIDFQ,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
7,48,327,01383949,48327,0500000US48327,Menard,Menard County,06,H1,G4020,NaN,NaN,NaN,A,2336237980,613559,+30.8852677,-099.8588613,"POLYGON ((-99.7712 30.71079, -99.7824 30.71078..."
11,48,189,01383880,48189,0500000US48189,Hale,Hale County,06,H1,G4020,352,38380,NaN,A,2602109424,246678,+34.0684364,-101.8228879,"POLYGON ((-102.09042 34.31313, -102.0889 34.31..."
13,48,011,01383791,48011,0500000US48011,Armstrong,Armstrong County,06,H1,G4020,108,11100,NaN,A,2354617584,12183672,+34.9641790,-101.3566363,"POLYGON ((-101.62512 35.0007, -101.62509 35.00..."
35,48,057,01383814,48057,0500000US48057,Calhoun,Calhoun County,06,H1,G4020,544,38920,NaN,A,1312947260,1361644522,+28.4417191,-096.5795739,"POLYGON ((-96.64344 28.7121, -96.64322 28.7121..."
38,48,077,01383824,48077,0500000US48077,Clay,Clay County,06,H1,G4020,NaN,48660,NaN,A,2819873723,72504932,+33.7859042,-098.2129174,"POLYGON ((-98.4236 34.03621, -98.42357 34.0391..."

In [4]:
# Create the df with data profiles
df = pd.read_parquet(
    "C:/Users/viole/dev/projects/portfolio/texas-county-dashboard/src/texas_county_dashboards/data/processed/texas_county_analytics.parquet"
)

In [5]:
county_map = counties.merge(
    df,
    on="GEOID"
)

In [6]:
counties[["GEOID", "NAME"]].head()

    GEOID       NAME
7   48327     Menard
11  48189       Hale
13  48011  Armstrong
35  48057    Calhoun
38  48077       Clay

In [7]:
df[["GEOID", "NAME"]].head()

   GEOID                    NAME
0  48001  Anderson County, Texas
1  48003   Andrews County, Texas
2  48005  Angelina County, Texas
3  48007   Aransas County, Texas
4  48009    Archer County, Texas