In [1]:
# Imports
import pandas as pd
import os
from dotenv import load_dotenv

from src.texas_county_dashboards.scripts.census_client import CensusClient
from src.texas_county_dashboards.analytics.county_analytics import CountyAnalytics

In [2]:
# Retrieve the api key
load_dotenv()
api_key = os.getenv("CENSUS_API_KEY")

census_client = CensusClient(
    api_key=api_key
)

analytics = CountyAnalytics(census_client=census_client)

df = analytics.load_data()

In [4]:
df.shape

(254, 41)

In [3]:
df.columns

Index(['state', 'county', 'GEOID', 'NAME', 'population', 'population_25_plus',
       'less_than_9th_grade', 'high_school_graduate', 'bachelors', 'masters',
       'professional', 'doctorate', 'population_16_plus', 'labor_force',
       'employed', 'unemployed', 'total_population', 'median_age',
       'male_population', 'female_population', 'white_population',
       'black_population', 'american_indian_population', 'asian_population',
       'native_hawaiian_population', 'other_race_population',
       'two_or_more_races_population', 'hispanic_population',
       'median_household_income', 'per_capita_income', 'poverty_universe',
       'population_below_poverty', 'households_with_snap', 'housing_units',
       'occupied_housing_units', 'vacant_housing_units',
       'owner_occupied_units', 'renter_occupied_units', 'median_home_value',
       'median_gross_rent', 'average_household_size'],
      dtype='str')

In [5]:
df.head()

,state,county,GEOID,NAME,population,population_25_plus,less_than_9th_grade,high_school_graduate,bachelors,masters,...,population_below_poverty,households_with_snap,housing_units,occupied_housing_units,vacant_housing_units,owner_occupied_units,renter_occupied_units,median_home_value,median_gross_rent,average_household_size
0,48,001,48001,"Anderson County, Texas",58439,42299,496,11227,4614,1373,...,8373,3161,20648,17579,3069,12716,4863,185300,1041,2.73
1,48,003,48003,"Andrews County, Texas",18610,11259,560,3125,1634,245,...,2872,891,7153,6844,309,5374,1470,195700,1305,2.69
2,48,005,48005,"Angelina County, Texas",87275,57523,1327,16177,6488,3173,...,13351,5405,37023,32271,4752,20650,11621,163500,1076,2.60
3,48,007,48007,"Aransas County, Texas",24876,19444,245,4959,4068,1146,...,3513,1071,15999,12478,3521,9578,2900,265400,1128,1.97
4,48,009,48009,"Archer County, Texas",8867,6339,39,1842,1132,362,...,808,227,3966,3468,498,2929,539,189100,770,2.54

In [6]:
calculated_metrics_df = analytics.calculate_metrics()

calculated_metrics_df.head()

,state,county,GEOID,NAME,population,population_25_plus,less_than_9th_grade,high_school_graduate,bachelors,masters,...,renter_occupied_units,median_home_value,median_gross_rent,average_household_size,bachelors_plus_pct,unemployment_rate,poverty_rate,homeownership_rate,vacancy_rate,percent_with_snap
0,48,001,48001,"Anderson County, Texas",58439,42299,496,11227,4614,1373,...,4863,185300,1041,2.73,15.392799,5.952275,17.364884,72.336310,14.863425,5.409059
1,48,003,48003,"Andrews County, Texas",18610,11259,560,3125,1634,245,...,1470,195700,1305,2.69,17.683631,3.319548,15.592595,78.521333,4.319866,4.787749
2,48,005,48005,"Angelina County, Texas",87275,57523,1327,16177,6488,3173,...,11621,163500,1076,2.60,17.944127,6.387687,15.758971,63.989340,12.835265,6.193068
3,48,007,48007,"Aransas County, Texas",24876,19444,245,4959,4068,1146,...,2900,265400,1128,1.97,28.810944,4.089980,14.242277,76.759096,22.007625,4.305355
4,48,009,48009,"Archer County, Texas",8867,6339,39,1842,1132,362,...,539,189100,770,2.54,25.366777,3.038869,9.173479,84.457901,12.556732,2.560054

In [7]:
analytics.highest_income_counties()

,state,county,GEOID,NAME,population,population_25_plus,less_than_9th_grade,high_school_graduate,bachelors,masters,...,renter_occupied_units,median_home_value,median_gross_rent,average_household_size,bachelors_plus_pct,unemployment_rate,poverty_rate,homeownership_rate,vacancy_rate,percent_with_snap
198,48,397,48397,"Rockwall County, Texas",123617,80968,991,13330,23430,9217,...,7203,415500,1992,2.98,44.490416,4.293739,4.038319,82.532677,5.376319,1.422943
42,48,085,48085,"Collin County, Texas",1163337,775100,11067,95454,264674,136526,...,147833,475600,1859,2.77,56.216746,4.169385,6.234559,64.518320,4.743985,1.097532
129,48,259,48259,"Kendall County, Texas",48567,34029,228,5676,10874,4279,...,3638,512700,1606,2.70,48.896529,4.736165,5.029487,79.493828,7.661479,1.636914
78,48,157,48157,"Fort Bend County, Texas",893767,581016,13870,83326,173177,85399,...,67442,374500,1807,3.03,50.229942,5.052496,7.573171,76.959684,4.227292,2.228993
60,48,121,48121,"Denton County, Texas",979561,662975,11596,92533,213469,91679,...,124469,437200,1728,2.68,49.443493,4.016277,7.072371,65.462885,4.342887,1.600615
245,48,491,48491,"Williamson County, Texas",672688,458124,6268,66818,140185,64158,...,84783,447000,1796,2.65,48.427718,3.879005,6.430709,66.399020,3.929654,1.649502
35,48,071,48071,"Chambers County, Texas",51498,32652,665,7817,5378,1304,...,3177,329500,1609,2.97,21.934338,7.270152,11.850837,81.560160,9.019380,1.932114
183,48,367,48367,"Parker County, Texas",165168,112004,1835,23604,24426,9467,...,10870,375900,1500,2.90,32.334559,3.976336,7.982400,80.739586,5.748259,1.739441
45,48,091,48091,"Comal County, Texas",183826,129685,1533,23883,36823,14761,...,16687,427200,1603,2.56,43.346571,3.939722,6.479516,76.613785,8.474750,1.692361
86,48,173,48173,"Glasscock County, Texas",1068,783,9,130,182,28,...,145,245200,648,2.32,29.246488,0.781250,8.895131,68.478261,10.331384,4.213483

In [8]:
analytics.largest_counties()

,state,county,GEOID,NAME,population,population_25_plus,less_than_9th_grade,high_school_graduate,bachelors,masters,...,renter_occupied_units,median_home_value,median_gross_rent,average_household_size,bachelors_plus_pct,unemployment_rate,poverty_rate,homeownership_rate,vacancy_rate,percent_with_snap
100,48,201,48201,"Harris County, Texas",4838303,3131200,123143,591033,660816,283069,...,795727,276600,1401,2.73,34.240164,6.731452,16.252995,54.715268,8.375578,4.866934
56,48,113,48113,"Dallas County, Texas",2621179,1709388,66181,325766,376976,167715,...,483826,303000,1565,2.63,35.735772,4.995076,13.918331,50.767499,7.721193,3.932505
219,48,439,48439,"Tarrant County, Texas",2167390,1412762,35688,280943,318633,132093,...,318750,323900,1547,2.73,34.771462,4.703530,11.105514,59.260959,7.214645,3.454247
14,48,029,48029,"Bexar County, Texas",2067341,1349274,32716,270642,263431,119010,...,309018,262200,1354,2.70,31.844533,5.784966,14.615025,58.849121,8.509101,5.028924
226,48,453,48453,"Travis County, Texas",1330015,941975,20196,108615,329250,147480,...,279582,523000,1744,2.23,56.560949,4.556961,10.928039,52.105621,5.578614,2.444033
42,48,085,48085,"Collin County, Texas",1163337,775100,11067,95454,264674,136526,...,147833,475600,1859,2.77,56.216746,4.169385,6.234559,64.518320,4.743985,1.097532
60,48,121,48121,"Denton County, Texas",979561,662975,11596,92533,213469,91679,...,124469,437200,1728,2.68,49.443493,4.016277,7.072371,65.462885,4.342887,1.600615
78,48,157,48157,"Fort Bend County, Texas",893767,581016,13870,83326,173177,85399,...,67442,374500,1807,3.03,50.229942,5.052496,7.573171,76.959684,4.227292,2.228993
107,48,215,48215,"Hidalgo County, Texas",891977,516001,20353,115498,72515,25290,...,87939,140900,957,3.27,20.633487,7.610964,26.665550,67.455313,12.427566,8.428132
70,48,141,48141,"El Paso County, Texas",870779,549086,20116,104131,95601,34808,...,107181,180400,1079,2.86,25.948941,6.002634,18.745586,64.229718,7.396831,6.649219

In [9]:
# Check for na values
df.isna().sum()

state                           0
county                          0
GEOID                           0
NAME                            0
population                      0
population_25_plus              0
less_than_9th_grade             0
high_school_graduate            0
bachelors                       0
masters                         0
professional                    0
doctorate                       0
population_16_plus              0
labor_force                     0
employed                        0
unemployed                      0
total_population                0
median_age                      0
male_population                 0
female_population               0
white_population                0
black_population                0
american_indian_population      0
asian_population                0
native_hawaiian_population      0
other_race_population           0
two_or_more_races_population    0
hispanic_population             0
median_household_income         0
per_capita_income               0
poverty_universe                0
population_below_poverty        0
households_with_snap            0
housing_units                   0
occupied_housing_units          0
vacant_housing_units            0
owner_occupied_units            0
renter_occupied_units           0
median_home_value               0
median_gross_rent               0
average_household_size          0
bachelors_plus_pct              0
unemployment_rate               0
poverty_rate                    0
homeownership_rate              0
vacancy_rate                    0
percent_with_snap               0
dtype: int64

In [10]:
df.dtypes

state                               str
county                              str
GEOID                               str
NAME                                str
population                        int64
population_25_plus                int64
less_than_9th_grade               int64
high_school_graduate              int64
bachelors                         int64
masters                           int64
professional                      int64
doctorate                         int64
population_16_plus                int64
labor_force                       int64
employed                          int64
unemployed                        int64
total_population                  int64
median_age                      float64
male_population                   int64
female_population                 int64
white_population                  int64
black_population                  int64
american_indian_population        int64
asian_population                  int64
native_hawaiian_population        int64
other_race_population             int64
two_or_more_races_population      int64
hispanic_population               int64
median_household_income           int64
per_capita_income                 int64
poverty_universe                  int64
population_below_poverty          int64
households_with_snap              int64
housing_units                     int64
occupied_housing_units            int64
vacant_housing_units              int64
owner_occupied_units              int64
renter_occupied_units             int64
median_home_value                 int64
median_gross_rent                 int64
average_household_size          float64
bachelors_plus_pct              float64
unemployment_rate               float64
poverty_rate                    float64
homeownership_rate              float64
vacancy_rate                    float64
percent_with_snap               float64
dtype: object

In [11]:
analytics.save_data(
    "C:/Users/viole/dev/projects/portfolio/texas-county-dashboard/src/texas_county_dashboards/data/processed/texas_county_analytics.parquet"
)